--- #YAML:1.0
name:                Xymon-Monitor-Informix
version:             0.06
abstract:            Hobbit / Xymon Informix Database Monitor
license:             ~
author:              
    - David Peters (davidp@electronf.com)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DBD::Informix:                 0.1
    DBI:                           0.1
    Test::Simple:                  0.44
    Xymon::Client:                 0.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
